const suggestions = [
  { value: 1, label: "JavaScript" },
  { value: 2, label: "Python" },
  { value: 3, label: "Java" },
  { value: 4, label: "C#" },
  { value: 5, label: "PHP" },
  { value: 6, label: "HTML" },
  { value: 7, label: "CSS" },
  { value: 8, label: "ReactJS" },
  { value: 9, label: "Angular" },
  { value: 10, label: "Vue.js" },
  { value: 11, label: "Node.js" },
  { value: 12, label: "Express" },
  { value: 13, label: "TypeScript" },
  { value: 14, label: "Ruby" },
  { value: 15, label: "Django" },
  { value: 16, label: "Flask" },
  { value: 17, label: "Spring Boot" },
  { value: 18, label: "MySQL" },
  { value: 19, label: "PostgreSQL" },
  { value: 20, label: "MongoDB" },
  { value: 21, label: "SQLite" },
  { value: 22, label: "AWS" },
  { value: 23, label: "Azure" },
  { value: 24, label: "Google Cloud Platform" },
  { value: 25, label: "Docker" },
  { value: 26, label: "Kubernetes" },
  { value: 27, label: "Git" },
  { value: 28, label: "REST API" },
  { value: 29, label: "GraphQL" },
  { value: 30, label: "Webpack" },
  { value: 31, label: "Babel" },
  { value: 32, label: "Linux" },
  { value: 33, label: "Shell Scripting" },
  { value: 34, label: "PowerShell" },
  { value: 35, label: "ASP.NET" },
  { value: 36, label: "Laravel" },
  { value: 37, label: "Bootstrap" },
  { value: 38, label: "jQuery" },
  { value: 39, label: "SASS" },
  { value: 40, label: "LESS" },
  { value: 41, label: "Redux" },
  { value: 42, label: "Next.js" },
  { value: 43, label: "Nuxt.js" },
  { value: 44, label: "Electron" },
  { value: 45, label: "JavaFX" },
  { value: 46, label: "Kotlin" },
  { value: 47, label: "Swift" },
  { value: 48, label: "Objective-C" },
  { value: 49, label: "C" },
  { value: 50, label: "C++" },
  { value: 51, label: "MATLAB" },
  { value: 52, label: "R" },
  { value: 53, label: "Scala" },
  { value: 54, label: "Go" },
  { value: 55, label: "Rust" },
  { value: 56, label: "Elixir" },
  { value: 57, label: "Haskell" },
  { value: 58, label: "Perl" },
  { value: 59, label: "VBA" },
  { value: 60, label: "Assembly" },
  { value: 61, label: "Jenkins" },
  { value: 62, label: "Travis CI" },
  { value: 63, label: "CircleCI" },
  { value: 64, label: "Ansible" },
  { value: 65, label: "Terraform" },
  { value: 66, label: "Pandas" },
  { value: 67, label: "NumPy" },
  { value: 68, label: "TensorFlow" },
  { value: 69, label: "PyTorch" },
  { value: 70, label: "Keras" },
  { value: 71, label: "OpenCV" },
  { value: 72, label: "Scikit-learn" },
  { value: 73, label: "Matplotlib" },
  { value: 74, label: "Seaborn" },
  { value: 75, label: "Hadoop" },
  { value: 76, label: "Spark" },
  { value: 77, label: "Apache Kafka" },
  { value: 78, label: "Redis" },
  { value: 79, label: "RabbitMQ" },
  { value: 80, label: "ElasticSearch" },
  { value: 81, label: "Logstash" },
  { value: 82, label: "Kibana" },
  { value: 83, label: "Figma" },
  { value: 84, label: "Adobe XD" },
  { value: 85, label: "Unity" },
  { value: 86, label: "Unreal Engine" },
  { value: 87, label: "Three.js" },
  { value: 88, label: "WebGL" },
  { value: 89, label: "GraphQL" },
  { value: 90, label: "OAuth" },
  { value: 91, label: "JWT" },
  { value: 92, label: "Microservices" },
  { value: 93, label: "Event-Driven Architecture" },
  { value: 94, label: "Agile" },
  { value: 95, label: "Scrum" },
  { value: 96, label: "CI/CD" },
  { value: 97, label: "DevOps" },
  { value: 98, label: "SEO" },
  { value: 99, label: "WordPress" },
  { value: 100, label: "Shopify" }
];

export default suggestions;
